listen: :PORT_PLACEHOLDER

tls:
  cert: /etc/hysteria/cert.pem
  key: /etc/hysteria/key.pem

auth:
  type: password
  password: "dalong-strong-password"

udp:
  enabled: true
  fallback_tcp: true

bandwidth:
  up: 100 mbps
  down: 100 mbps
