app = "hy2-flyio-server"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 443
  protocol = "udp"

  [[services.ports]]
    port = 443
    protocol = "udp"

  [[services.ports]]
    port = 443
    protocol = "tcp"

  [[services.udp_checks]]
    interval = "10s"
    timeout = "2s"

