app = "hy2-flyio-server"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "udp"

  [[services.ports]]
    port = 8080
    protocol = "udp"

  [[services.udp_checks]]
    interval = "10s"
    timeout = "2s"
