app = "hy2-flyio-server"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[processes]
app = "/entrypoint.sh"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    protocol = "tcp"

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
